Data:
  DATA_DIR_ZIP: artifacts/data/yellow_tripdata_2019-04.csv.zip
  DATA_FILE_NAME: yellow_tripdata_2019-04.csv
  DATA_DIR: artifacts/data/

QA:
  PERCENTILE_DATAFRAME_PATH: artifacts/QA
  PERCENTILE_DATAFRAME_FILE: percentiles.csv

Model:
  MODEL_PATH: artifacts/models
  MODEL_FILE: best_model.pickl 