name: taxi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ensure
  - ipykernel
  - pip
  - pip:
    - Pandas
    - PyYAML
    - python-box
    - Numpy
    - scikit-learn
    - zip-files
    - matplotlib
    - seaborn
    - plotly
    - click
    - tqdm
    - loguru
    - nbformat
    - mlflow
    - requests
